import {
  differenceInCalendarDays,
  endOfMonth,
  format,
  startOfMonth,
  subDays,
  subMonths,
} from "date-fns";
import { CalendarClock, Clock, Flame, PieChart, Tag, Target } from "lucide-react";

import { Amount } from "@/components/amount";
import { CategoryIcon } from "@/components/category-icon";
import { SpendHero } from "@/components/home/spend-hero";
import { SalaryPrompt } from "@/components/salary-prompt";
import { orderAccounts } from "@/lib/account-order";
import { Tile, TileHeadline } from "@/components/home/tile";
import { WalletStack } from "@/components/home/wallet-stack";
import { capState } from "@/lib/cap-state";
import { isoDate, parseDate } from "@/lib/dates";
import { formatCents } from "@/lib/money";
import { spendingSegments } from "@/lib/spending-segments";
import { cn } from "@/lib/utils";
import { parseTransactionFilters } from "@/lib/validators/transaction";
import { requireUser } from "@/server/auth-context";
import { getBudgetProgress } from "@/server/queries/budgets";
import {
  getCategoryPace,
  getMonthTotals,
  getNextPayday,
  getSpendableBalance,
  getSpentSince,
  getUncategorisedCount,
  getUpcomingBills,
} from "@/server/queries/overview";
import {
  listAccountBalances,
  listCategoriesForUser,
  listTransactions,
} from "@/server/queries/transactions";

export const metadata = { title: "Tillpay" };

export default async function HomePage() {
  const user = await requireUser();
  const today = new Date();

  // Recurring transactions are generated by the cron job, not on page load.

  // The cycle runs until the next salary (or the end of the month if there's none).
  const payday = await getNextPayday(user.id);
  const runsUntil = payday ? parseDate(payday) : endOfMonth(today);

  // go back until the cycle start is not in the future
  let cycleStart = payday ? subMonths(runsUntil, 1) : startOfMonth(today);
  while (cycleStart > today) {
    cycleStart = subMonths(cycleStart, 1);
  }

  const daysLeft = Math.max(1, differenceInCalendarDays(runsUntil, today));
  const cycleDays = Math.max(1, differenceInCalendarDays(runsUntil, cycleStart));

  const [
    balanceCents,
    bills,
    pace,
    uncategorised,
    month,
    budgets,
    accounts,
    spentThisCycle,
    recent,
    categories,
  ] = await Promise.all([
    getSpendableBalance(user.id),
    getUpcomingBills(user.id, isoDate(runsUntil)),
    getCategoryPace(user.id),
    getUncategorisedCount(user.id),
    getMonthTotals(user.id),
    getBudgetProgress(user.id, isoDate(startOfMonth(today))),
    listAccountBalances(user.id),
    getSpentSince(user.id, isoDate(cycleStart)),
    listTransactions(user.id, parseTransactionFilters({})),
    listCategoriesForUser(user.id),
  ]);

  const committedCents = bills[0]?.committedCents ?? 0;
  const safeToSpendCents = balanceCents - committedCents;
  const perDayCents = Math.floor(safeToSpendCents / daysLeft);

  const cycleBudget = safeToSpendCents + spentThisCycle;
  const usedFraction = cycleBudget > 0 ? spentThisCycle / cycleBudget : 0;

  const overspending = pace
    .filter((row) => row.usualCents !== null && row.usualCents > 0)
    .map((row) => ({
      ...row,
      ratio: row.thisMonthCents / (row.usualCents as number),
    }))
    .filter((row) => row.ratio >= 1.2)
    .sort((a, b) => b.thisMonthCents - a.thisMonthCents)[0];

  const overCap = budgets.filter((budget) => budget.used > 1);
  const segments = spendingSegments(pace, month.spentCents);
  const latest = recent.rows.slice(0, 5);
  const hasAlerts = uncategorised > 0 || !!overspending;

  const dayLabel = (date: string) =>
    date === isoDate(today)
      ? "Today"
      : date === isoDate(subDays(today, 1))
        ? "Yesterday"
        : format(parseDate(date), "d MMM");

  return (
    <main className="mx-auto w-full max-w-6xl px-4 py-6 lg:py-10">
      <header className="mb-6 lg:mb-8">
        <p className="text-sm font-medium text-muted-foreground">
          {format(today, "EEEE, d MMMM")}
        </p>
        <h1 className="text-3xl font-semibold tracking-tight lg:text-4xl">Your money</h1>
      </header>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
        <div className="lg:col-span-7">
          <SpendHero
            safeToSpendCents={safeToSpendCents}
            perDayCents={perDayCents}
            payday={runsUntil}
            cycleDays={cycleDays}
            daysLeft={daysLeft}
            usedFraction={usedFraction}
            balanceCents={balanceCents}
            committedCents={committedCents}
            hasSalary={payday !== null}
            salaryPrompt={
              <SalaryPrompt
                accounts={orderAccounts(accounts)
                  .filter((account) => account.kind !== "savings")
                  .map(({ id, name }) => ({ id, name }))}
                salaryCategoryId={
                  categories.find(
                    (category) => category.kind === "income" && category.name === "Salary",
                  )?.id ?? null
                }
                today={isoDate(today)}
              />
            }
          />
        </div>
        <div className="lg:col-span-5">
          <WalletStack accounts={accounts} />
        </div>
      </div>

      <div className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 lg:gap-6">
        <Tile
          title="Spending"
          icon={PieChart}
          tone="text-tone-spending"
          aside={format(today, "MMMM")}
          href="/reports"
        >
          <TileHeadline>{formatCents(month.spentCents, "EUR")}</TileHeadline>
          <p className="mt-1 text-base text-muted-foreground">
            {formatCents(month.incomeCents, "EUR")} came in
          </p>

          {segments.length > 0 ? (
            <>
              <div className="mt-5 flex h-3 gap-0.5 overflow-hidden rounded-full">
                {segments.map((segment) => (
                  <span
                    key={segment.id}
                    className="h-full bg-muted-foreground/30"
                    style={{
                      width: `${(segment.cents / month.spentCents) * 100}%`,
                      ...(segment.color ? { backgroundColor: segment.color } : {}),
                    }}
                  />
                ))}
              </div>
              <ul className="mt-4 flex flex-col gap-2">
                {segments.map((segment) => (
                  <li key={segment.id} className="flex items-center gap-2.5 text-base">
                    <span
                      className="size-2.5 shrink-0 rounded-full bg-muted-foreground/30"
                      style={segment.color ? { backgroundColor: segment.color } : undefined}
                      aria-hidden
                    />
                    <span className="truncate">{segment.name}</span>
                    <span className="ml-auto tabular-nums text-muted-foreground">
                      {formatCents(segment.cents, "EUR")}
                    </span>
                  </li>
                ))}
              </ul>
            </>
          ) : null}
        </Tile>

        <Tile
          title="Coming up"
          icon={CalendarClock}
          tone="text-tone-bills"
          aside={`before ${format(runsUntil, "d MMM")}`}
          href="/recurring"
        >
          <TileHeadline>
            {bills.length === 0
              ? "Nothing due"
              : `${bills.length} ${bills.length === 1 ? "bill" : "bills"}`}
          </TileHeadline>
          <ul className="mt-4 flex flex-col divide-y">
            {bills.slice(0, 4).map((bill) => (
              <li key={bill.id} className="flex items-baseline gap-3 py-2.5 text-base first:pt-0">
                <span className="min-w-0 flex-1">
                  <span className="block truncate">{bill.description}</span>
                  <span className="block text-sm text-muted-foreground">
                    {format(parseDate(bill.dueOn), "EEE, d MMM")}
                  </span>
                </span>
                <span className="shrink-0 tabular-nums">
                  {formatCents(Math.abs(bill.amountCents), "EUR")}
                </span>
              </li>
            ))}
          </ul>
        </Tile>

        <Tile
          title="Budgets"
          icon={Target}
          tone="text-tone-budgets"
          href="/budgets"
          className="md:col-span-2 lg:col-span-1"
        >
          {budgets.length === 0 ? (
            <p className="text-base text-muted-foreground">
              No limits set yet. Add one to get a heads-up before a category runs away.
            </p>
          ) : (
            <>
              <TileHeadline>
                {overCap.length > 0 ? `${overCap.length} over` : "All within"}
              </TileHeadline>
              <ul className="mt-4 flex flex-col gap-3.5">
                {budgets.slice(0, 4).map((budget) => (
                  <li key={budget.id} className="flex flex-col gap-1.5">
                    <span className="flex items-baseline justify-between gap-3 text-base">
                      <span className="truncate">{budget.categoryName}</span>
                      <span className="tabular-nums text-muted-foreground">
                        {Math.round(budget.used * 100)}%
                      </span>
                    </span>
                    <span className="h-2 overflow-hidden rounded-full bg-muted">
                      <span
                        className={cn(
                          "block h-full rounded-full",
                          { over: "bg-negative", near: "bg-warning", ok: "bg-tone-budgets" }[
                            capState(budget.used)
                          ],
                        )}
                        style={{ width: `${Math.min(100, budget.used * 100)}%` }}
                      />
                    </span>
                  </li>
                ))}
              </ul>
            </>
          )}
        </Tile>
      </div>

      <div className="mt-4 grid grid-cols-1 gap-4 lg:mt-6 lg:grid-cols-3 lg:gap-6">
        <Tile
          title="Latest"
          icon={Clock}
          href="/transactions"
          aside="See all"
          className={hasAlerts ? "lg:col-span-2" : "lg:col-span-3"}
        >
          {latest.length === 0 ? (
            <p className="text-base text-muted-foreground">Nothing recorded yet.</p>
          ) : (
            <ul className="-my-2 flex flex-col divide-y">
              {latest.map((row) => {
                const isTransfer = row.type === "transfer";
                return (
                  <li key={row.id} className="flex items-center gap-3 py-3">
                    <CategoryIcon
                      category={row.categoryName}
                      color={row.categoryColor}
                      isTransfer={isTransfer}
                      className="flex size-10 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground"
                    />
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-base">
                        {row.description ?? row.categoryName ?? "Transfer"}
                      </span>
                      <span className="block truncate text-sm text-muted-foreground">
                        {isTransfer ? "Transfer" : (row.categoryName ?? "No category")} ·{" "}
                        {dayLabel(row.occurredOn)}
                      </span>
                    </span>
                    <Amount
                      cents={row.amountCents}
                      currency={row.currency}
                      colored={!isTransfer}
                      className="shrink-0 text-base font-medium"
                    />
                  </li>
                );
              })}
            </ul>
          )}
        </Tile>

        {hasAlerts ? (
          <div className="flex flex-col gap-4 lg:gap-6">
            {overspending ? (
              <Tile
                title="Running high"
                icon={Flame}
                tone="text-warning"
                href={`/transactions?categoryId=${overspending.id}`}
              >
                <TileHeadline>{overspending.name}</TileHeadline>
                <p className="mt-1 text-base text-muted-foreground">
                  {formatCents(overspending.thisMonthCents, "EUR")} so far this month,
                  usually {formatCents(overspending.usualCents as number, "EUR")} by now.
                </p>
              </Tile>
            ) : null}

            {uncategorised > 0 ? (
              <Tile
                title="To sort out"
                icon={Tag}
                tone="text-muted-foreground"
                href="/transactions?uncategorised=true"
              >
                <TileHeadline>
                  {uncategorised} {uncategorised === 1 ? "transaction" : "transactions"}
                </TileHeadline>
                <p className="mt-1 text-base text-muted-foreground">without a category.</p>
              </Tile>
            ) : null}
          </div>
        ) : null}
      </div>
    </main>
  );
}
